import type { EquipmentCategory, EquipmentDefinition } from './types';

// ============================================================
// Massive Equipment Catalog (200+ Equipment Items)
// Grouped into Categories:
// 1. Camera & Lenses & Rigs (40 items)
// 2. Lighting & Modifiers & FX (45 items)
// 3. Audio & Microphones & Sound Treatment (40 items)
// 4. Furniture, Desks, Seating & Staging (35 items)
// 5. Tech, Computing, Monitors & Switchers (30 items)
// 6. Power, Cables, Backup & Accessories (25 items)
// ============================================================

export const EXTENDED_EQUIPMENT_CATALOG: Record<string, EquipmentDefinition> = {
  // ------------------------------------------------------------
  // 1. CAMERAS, LENSES, MOUNTS & RIGS (40 items)
  // ------------------------------------------------------------
  'camera': {
    id: 'camera',
    name: 'Cinema / Mirrorless Rig on Tripod',
    icon: '🎥',
    category: 'camera',
    dimensions: { width: 0.35, depth: 0.35, height: 1.5 },
    watts: 25,
    defaultPriceGHS: 3200,
    defaultPriceNGN: 165000,
    color: 0x2a2826,
    description: 'Full-frame 4K cinema camera with matte box on fluid-head tripod',
  },
  'cinema-camera-rig': {
    id: 'cinema-camera-rig',
    name: 'RED / ARRI Cinema Production Rig',
    icon: '🎬',
    category: 'camera',
    dimensions: { width: 0.45, depth: 0.45, height: 1.65 },
    watts: 65,
    defaultPriceGHS: 12500,
    defaultPriceNGN: 650000,
    color: 0x1f1e1d,
    description: 'High-end cinema rig with follow focus, V-mount battery, and 7-inch monitor',
  },
  'phone-gimbal': {
    id: 'phone-gimbal',
    name: 'Smartphone on 3-Axis Gimbal',
    icon: '📱',
    category: 'camera',
    dimensions: { width: 0.15, depth: 0.15, height: 0.4 },
    watts: 0,
    defaultPriceGHS: 1200,
    defaultPriceNGN: 62000,
    color: 0x2a2826,
    description: 'Smartphone clamped in 3-axis motorized stabilizer',
  },
  'phone-tripod-mirror': {
    id: 'phone-tripod-mirror',
    name: 'Smartphone Desk Tripod + Rear Mirror',
    icon: '📱',
    category: 'camera',
    dimensions: { width: 0.18, depth: 0.18, height: 0.45 },
    watts: 0,
    defaultPriceGHS: 180,
    defaultPriceNGN: 9500,
    color: 0x1e293b,
    description: 'Budget smartphone clamp mount with angled rear mirror so you can use the superior 4K back camera while monitoring yourself',
    isMountableOnTable: true,
  },
  'ring-light': {
    id: 'ring-light',
    name: '18-Inch LED Ring Light',
    icon: '💡',
    category: 'lighting',
    dimensions: { width: 0.5, depth: 0.1, height: 1.8 },
    watts: 45,
    defaultPriceGHS: 280,
    defaultPriceNGN: 14500,
    color: 0xf5f1ea,
    description: 'Circular bi-color ring light with center cold shoe mount',
  },
  'camera-slider': {
    id: 'camera-slider',
    name: 'Motorized Camera Slider Rail (80cm)',
    icon: '🔲',
    category: 'camera',
    dimensions: { width: 0.15, depth: 0.8, height: 0.15 },
    watts: 15,
    defaultPriceGHS: 600,
    defaultPriceNGN: 31000,
    color: 0x4a4744,
    description: 'Programmable carbon fiber time-lapse and interview slider',
  },
  'webcam': {
    id: 'webcam',
    name: '4K Ultra-HD Streaming Webcam',
    icon: '📹',
    category: 'camera',
    dimensions: { width: 0.12, depth: 0.08, height: 0.08 },
    watts: 5,
    defaultPriceGHS: 450,
    defaultPriceNGN: 23000,
    color: 0x222222,
    description: '4K HDR wide-angle webcam with magnetic privacy shutter',
    isMountableOnTable: true,
  },
  'drone': {
    id: 'drone',
    name: '4K Aerial Quadcopter Drone',
    icon: '🛸',
    category: 'camera',
    dimensions: { width: 0.35, depth: 0.35, height: 0.12 },
    watts: 0,
    defaultPriceGHS: 2400,
    defaultPriceNGN: 124000,
    color: 0x555555,
    description: 'Foldable cinematic drone with 3-axis stabilized Hasselblad sensor',
  },
  'overhead-rig': {
    id: 'overhead-rig',
    name: 'Articulating Overhead Camera Boom',
    icon: '🏗️',
    category: 'camera',
    dimensions: { width: 0.35, depth: 0.75, height: 2.1 },
    watts: 0,
    defaultPriceGHS: 520,
    defaultPriceNGN: 27000,
    color: 0x33312e,
    description: 'Counterweighted heavy overhead boom arm for flatlays and food prep',
  },
  'floor-monitor': {
    id: 'floor-monitor',
    name: '24-Inch Stage Floor Wedge Monitor',
    icon: '📺',
    category: 'camera',
    dimensions: { width: 0.6, depth: 0.35, height: 0.42 },
    watts: 35,
    defaultPriceGHS: 750,
    defaultPriceNGN: 39000,
    color: 0x22201d,
    description: '45-degree angled floor confidence monitor for hosts and actors',
  },
  'multi-cam-switcher': {
    id: 'multi-cam-switcher',
    name: '4-Channel Live Broadcast Switcher',
    icon: '🎚️',
    category: 'camera',
    dimensions: { width: 0.32, depth: 0.18, height: 0.08 },
    watts: 20,
    defaultPriceGHS: 820,
    defaultPriceNGN: 42500,
    color: 0x22201e,
    description: 'ATEM-style 4-HDMI video mixer console with hardware transition lever',
    isMountableOnTable: true,
  },
  'teleprompter': {
    id: 'teleprompter',
    name: '70/30 Beam-Splitter Glass Teleprompter',
    icon: '📜',
    category: 'camera',
    dimensions: { width: 0.35, depth: 0.4, height: 0.35 },
    watts: 15,
    defaultPriceGHS: 650,
    defaultPriceNGN: 33500,
    color: 0x222222,
    description: 'Optical glass prompter hood mounted directly on camera lens',
  },
  'ptz-robotic-camera': {
    id: 'ptz-robotic-camera',
    name: 'NDI PTZ Robotic Studio Camera',
    icon: '🤖',
    category: 'camera',
    dimensions: { width: 0.22, depth: 0.22, height: 0.28 },
    watts: 18,
    defaultPriceGHS: 3600,
    defaultPriceNGN: 185000,
    color: 0x2e2c2a,
    description: 'Remote-controlled 30x optical zoom PTZ camera with tally light',
  },
  'jib-crane-arm': {
    id: 'jib-crane-arm',
    name: '12ft Studio Camera Jib Crane',
    icon: '📐',
    category: 'camera',
    dimensions: { width: 0.6, depth: 2.4, height: 2.3 },
    watts: 0,
    defaultPriceGHS: 4800,
    defaultPriceNGN: 245000,
    color: 0x282624,
    description: 'Telescoping heavy-duty camera crane for sweeping cinematic studio moves',
  },
  'action-cam-helmet': {
    id: 'action-cam-helmet',
    name: 'POV Action Camera & Chest Harness',
    icon: '📷',
    category: 'camera',
    dimensions: { width: 0.1, depth: 0.1, height: 0.1 },
    watts: 0,
    defaultPriceGHS: 420,
    defaultPriceNGN: 21500,
    color: 0x111111,
    description: 'Ultra-wide 5.3K waterproof action camera with horizon leveling',
  },
  'anamorphic-lens-set': {
    id: 'anamorphic-lens-set',
    name: 'Full-Frame Anamorphic Prime Lens Case',
    icon: '🔍',
    category: 'camera',
    dimensions: { width: 0.45, depth: 0.35, height: 0.2 },
    watts: 0,
    defaultPriceGHS: 5400,
    defaultPriceNGN: 280000,
    color: 0x1a1918,
    description: 'Hard flight case containing 24mm, 35mm, 50mm, 85mm 1.33x anamorphic lenses',
    isMountableOnTable: true,
  },
  'wireless-video-transmitter': {
    id: 'wireless-video-transmitter',
    name: 'Zero-Latency Wireless HDMI/SDI Tx/Rx',
    icon: '📡',
    category: 'camera',
    dimensions: { width: 0.12, depth: 0.08, height: 0.15 },
    watts: 10,
    defaultPriceGHS: 850,
    defaultPriceNGN: 44000,
    color: 0x222222,
    description: '1000ft wireless video transmission pair with dual dipole antennas',
  },
  'directors-monitor': {
    id: 'directors-monitor',
    name: '7-Inch High-Bright Director Monitor Cage',
    icon: '🖥️',
    category: 'camera',
    dimensions: { width: 0.24, depth: 0.12, height: 0.18 },
    watts: 20,
    defaultPriceGHS: 1450,
    defaultPriceNGN: 75000,
    color: 0x2a2826,
    description: '2200-nit daylight viewable production monitor with wooden side grips',
  },
  'steadicam-vest': {
    id: 'steadicam-vest',
    name: 'Steadicam Iso-Elastic Arm & Vest',
    icon: '🥋',
    category: 'camera',
    dimensions: { width: 0.45, depth: 0.45, height: 1.1 },
    watts: 0,
    defaultPriceGHS: 2900,
    defaultPriceNGN: 150000,
    color: 0x1c1b1a,
    description: 'Ergonomic dual-spring arm body vest for stabilizing heavy cine rigs',
  },
  'motorized-pan-tilt-head': {
    id: 'motorized-pan-tilt-head',
    name: 'Programmable 2-Axis Motion Pan-Tilt Head',
    icon: '🔄',
    category: 'camera',
    dimensions: { width: 0.18, depth: 0.18, height: 0.22 },
    watts: 12,
    defaultPriceGHS: 720,
    defaultPriceNGN: 37000,
    color: 0x333333,
    description: 'App-controlled repeat tracking head for time-lapses and multi-pass VFX',
  },
  'dolly-track-system': {
    id: 'dolly-track-system',
    name: 'Straight Studio Dolly Track (3m)',
    icon: '🛤️',
    category: 'camera',
    dimensions: { width: 0.75, depth: 3.0, height: 0.1 },
    watts: 0,
    defaultPriceGHS: 1100,
    defaultPriceNGN: 57000,
    color: 0x444444,
    description: 'Precision aluminum pipe rail track with smooth floor skate wheels',
  },
  'gimbal-ring-grip': {
    id: 'gimbal-ring-grip',
    name: 'Carbon Fiber Ring Grip Handle for Gimbal',
    icon: '⭕',
    category: 'camera',
    dimensions: { width: 0.65, depth: 0.2, height: 0.65 },
    watts: 0,
    defaultPriceGHS: 380,
    defaultPriceNGN: 19500,
    color: 0x1f1e1d,
    description: 'Dual-handed 360 ring grip with remote focus wheel integration',
  },
  'matte-box-filter-kit': {
    id: 'matte-box-filter-kit',
    name: 'Carbon Matte Box & 4x5.65 ND Filters',
    icon: '🎴',
    category: 'camera',
    dimensions: { width: 0.25, depth: 0.15, height: 0.2 },
    watts: 0,
    defaultPriceGHS: 480,
    defaultPriceNGN: 25000,
    color: 0x111111,
    description: 'Swing-away matte box with carbon top flag and 3-stage rotating filter trays',
  },
  'monopod-fluid-base': {
    id: 'monopod-fluid-base',
    name: 'Carbon Fiber Monopod with Fluid 3-Leg Base',
    icon: '🦯',
    category: 'camera',
    dimensions: { width: 0.28, depth: 0.28, height: 1.6 },
    watts: 0,
    defaultPriceGHS: 340,
    defaultPriceNGN: 17500,
    color: 0x2d2b29,
    description: 'Fast-deploy run-and-gun monopod with locking ball base',
  },
  'macro-probe-lens': {
    id: 'macro-probe-lens',
    name: '24mm 2:1 Waterproof Macro Probe Lens',
    icon: '🔬',
    category: 'camera',
    dimensions: { width: 0.08, depth: 0.42, height: 0.08 },
    watts: 5,
    defaultPriceGHS: 2100,
    defaultPriceNGN: 108000,
    color: 0x222222,
    description: 'Slender barrel probe lens with built-in front LED ring for bug-eye perspective',
  },
  'wireless-follow-focus': {
    id: 'wireless-follow-focus',
    name: 'Wireless Motorized Follow Focus Kit',
    icon: '⚙️',
    category: 'camera',
    dimensions: { width: 0.12, depth: 0.1, height: 0.08 },
    watts: 8,
    defaultPriceGHS: 620,
    defaultPriceNGN: 32000,
    color: 0x292827,
    description: 'High-torque focus motor with handwheel marking disc and A/B hard stops',
  },
  'gopro-360-max': {
    id: 'gopro-360-max',
    name: 'Dual-Lens 360-Degree Spherical Camera',
    icon: '🌐',
    category: 'camera',
    dimensions: { width: 0.09, depth: 0.07, height: 0.14 },
    watts: 0,
    defaultPriceGHS: 580,
    defaultPriceNGN: 30000,
    color: 0x333333,
    description: 'Dual back-to-back 180-degree fisheye lenses for full VR capture',
  },
  'heavy-duty-spreader-tripod': {
    id: 'heavy-duty-spreader-tripod',
    name: '100mm Bowl Studio Tripod with Ground Spreader',
    icon: '🪜',
    category: 'camera',
    dimensions: { width: 0.55, depth: 0.55, height: 1.6 },
    watts: 0,
    defaultPriceGHS: 1200,
    defaultPriceNGN: 62000,
    color: 0x22201d,
    description: 'Twin-leg aluminum cine tripod supporting up to 25kg camera rigs',
  },
  'tabletop-mini-tripod': {
    id: 'tabletop-mini-tripod',
    name: 'Heavy Steel Tabletop Ball-Head Tripod',
    icon: '📐',
    category: 'camera',
    dimensions: { width: 0.18, depth: 0.18, height: 0.22 },
    watts: 0,
    defaultPriceGHS: 110,
    defaultPriceNGN: 5500,
    color: 0x282624,
    description: 'Compact metal desk tripod for podcast b-roll or micro cameras',
    isMountableOnTable: true,
  },
  'suction-cup-car-mount': {
    id: 'suction-cup-car-mount',
    name: 'Triple Suction Cup Vehicle Camera Rig',
    icon: '🚗',
    category: 'camera',
    dimensions: { width: 0.45, depth: 0.45, height: 0.3 },
    watts: 0,
    defaultPriceGHS: 390,
    defaultPriceNGN: 20000,
    color: 0x1f1e1d,
    description: 'Industrial 6-inch vacuum suction cups for windshield and hood filming',
  },
  'electronic-viewfinder': {
    id: 'electronic-viewfinder',
    name: 'OLED Cinema Electronic Viewfinder (EVF)',
    icon: '👁️',
    category: 'camera',
    dimensions: { width: 0.18, depth: 0.08, height: 0.1 },
    watts: 6,
    defaultPriceGHS: 890,
    defaultPriceNGN: 46000,
    color: 0x181716,
    description: 'High-resolution micro-OLED EVF with diopter adjustment and false color',
  },
  'cold-shoe-monitor-mount': {
    id: 'cold-shoe-monitor-mount',
    name: 'Swivel & Tilt Damping Cold Shoe Mount',
    icon: '🔩',
    category: 'camera',
    dimensions: { width: 0.06, depth: 0.04, height: 0.08 },
    watts: 0,
    defaultPriceGHS: 45,
    defaultPriceNGN: 2300,
    color: 0x333333,
    description: 'Aluminum CNC friction mount for on-camera microphones and monitors',
  },
  'lens-filter-matte-case': {
    id: 'lens-filter-matte-case',
    name: 'Magnetic Circular VND & Polarizer Filter Case',
    icon: '💼',
    category: 'camera',
    dimensions: { width: 0.2, depth: 0.15, height: 0.06 },
    watts: 0,
    defaultPriceGHS: 240,
    defaultPriceNGN: 12500,
    color: 0x1e1d1c,
    description: 'Padded zipper pouch with 82mm Variable ND and Circular Polarizer glass',
    isMountableOnTable: true,
  },
  'quick-release-baseplate': {
    id: 'quick-release-baseplate',
    name: 'Arca-Swiss / Manfrotto Quick Release Baseplate',
    icon: '🧱',
    category: 'camera',
    dimensions: { width: 0.1, depth: 0.08, height: 0.03 },
    watts: 0,
    defaultPriceGHS: 65,
    defaultPriceNGN: 3400,
    color: 0x222222,
    description: 'Dual-compatible quick disconnect plate with safety drop lock pin',
  },
  'v-mount-plate-rods': {
    id: 'v-mount-plate-rods',
    name: '15mm Rod V-Mount Battery Adapter Plate',
    icon: '🔋',
    category: 'camera',
    dimensions: { width: 0.14, depth: 0.1, height: 0.15 },
    watts: 0,
    defaultPriceGHS: 180,
    defaultPriceNGN: 9500,
    color: 0x1f1e1d,
    description: 'D-Tap, USB-C PD and DC power distribution block on 15mm rail bracket',
  },
  'cable-strain-relief-clamp': {
    id: 'cable-strain-relief-clamp',
    name: 'Universal HDMI/USB-C Cable Clamp Lock',
    icon: '🗜️',
    category: 'camera',
    dimensions: { width: 0.08, depth: 0.03, height: 0.04 },
    watts: 0,
    defaultPriceGHS: 35,
    defaultPriceNGN: 1800,
    color: 0x444444,
    description: 'Protects fragile camera camera micro-HDMI and USB ports from yank damage',
  },
  'cage-top-handle': {
    id: 'cage-top-handle',
    name: 'NATO Rail Quick-Release Wooden Top Handle',
    icon: '🪓',
    category: 'camera',
    dimensions: { width: 0.16, depth: 0.05, height: 0.09 },
    watts: 0,
    defaultPriceGHS: 95,
    defaultPriceNGN: 4900,
    color: 0x5a3e28,
    description: 'Ergonomic rosewood sculpted grip with ARRI locating pins',
  },
  'lens-cleaning-sensor-kit': {
    id: 'lens-cleaning-sensor-kit',
    name: 'Pro Sensor Swabs & Optical Air Blower Kit',
    icon: '🧹',
    category: 'camera',
    dimensions: { width: 0.18, depth: 0.12, height: 0.08 },
    watts: 0,
    defaultPriceGHS: 55,
    defaultPriceNGN: 2800,
    color: 0x2e2c2a,
    description: 'Full-frame sensor swabs, rocket blower, and micro-fiber lens cloths',
    isMountableOnTable: true,
  },
  'tripod-rolling-dolly': {
    id: 'tripod-rolling-dolly',
    name: 'Foldable Universal Tripod Rolling Wheel Dolly',
    icon: '🛒',
    category: 'camera',
    dimensions: { width: 0.65, depth: 0.65, height: 0.18 },
    watts: 0,
    defaultPriceGHS: 210,
    defaultPriceNGN: 11000,
    color: 0x222222,
    description: '3-wheel locking rubber caster dolly for smooth floor pans and shifts',
  },
  'slate-clapperboard': {
    id: 'slate-clapperboard',
    name: 'Acrylic Color Production Slate Clapperboard',
    icon: '🎬',
    category: 'camera',
    dimensions: { width: 0.3, depth: 0.03, height: 0.25 },
    watts: 0,
    defaultPriceGHS: 75,
    defaultPriceNGN: 3900,
    color: 0xffffff,
    description: 'Dry-erase production slate with magnetic sound sync clicker sticks',
    isMountableOnTable: true,
  },
  'lens-calibration-chart': {
    id: 'lens-calibration-chart',
    name: 'Backlit Lens Autofocus Calibration Target',
    icon: '🎯',
    category: 'camera',
    dimensions: { width: 0.45, depth: 0.15, height: 0.35 },
    watts: 0,
    defaultPriceGHS: 140,
    defaultPriceNGN: 7200,
    color: 0xdddddd,
    description: 'Siemens star resolution chart and 45-degree focus ruler stand',
  },

  // ------------------------------------------------------------
  // 2. LIGHTING & MODIFIERS & EFFECTS (45 items)
  // ------------------------------------------------------------
  'led-light': {
    id: 'led-light',
    name: '60W COB LED Studio Light',
    icon: '💡',
    category: 'lighting',
    dimensions: { width: 0.3, depth: 0.2, height: 1.6 },
    watts: 60,
    defaultPriceGHS: 650,
    defaultPriceNGN: 33500,
    color: 0x3a3836,
    description: 'Compact 60W continuous daylight COB light with Bowens mount',
  },
  'softbox': {
    id: 'softbox',
    name: '90cm Octabox with Honeycomb Grid',
    icon: '📦',
    category: 'lighting',
    dimensions: { width: 0.8, depth: 0.8, height: 1.8 },
    watts: 150,
    defaultPriceGHS: 850,
    defaultPriceNGN: 44000,
    color: 0x1f1e1d,
    description: 'Deep parabolic softbox with inner diffuser and directional grid',
  },
  'fresnel': {
    id: 'fresnel',
    name: '300W Bi-Color Fresnel Spotlight',
    icon: '🔦',
    category: 'lighting',
    dimensions: { width: 0.4, depth: 0.4, height: 1.9 },
    watts: 300,
    defaultPriceGHS: 1400,
    defaultPriceNGN: 72000,
    color: 0x222222,
    description: 'High-power glass fresnel focusing beam from 15 to 45 degrees',
  },
  'rgb-tube': {
    id: 'rgb-tube',
    name: '4ft Pixel RGB LED Tube Light',
    icon: '🪄',
    category: 'lighting',
    dimensions: { width: 0.08, depth: 0.08, height: 1.2 },
    watts: 30,
    defaultPriceGHS: 350,
    defaultPriceNGN: 18000,
    color: 0x9922ee,
    description: 'Full-spectrum RGB pixel tube with built-in effects and magnets',
  },
  'desk-lamp': {
    id: 'desk-lamp',
    name: 'Architect Metal Desk Lamp',
    icon: '🛋️',
    category: 'lighting',
    dimensions: { width: 0.2, depth: 0.2, height: 0.5 },
    watts: 15,
    defaultPriceGHS: 120,
    defaultPriceNGN: 6200,
    color: 0xe8e4de,
    description: 'Spring-balanced arm warm glow desk lamp',
    isMountableOnTable: true,
  },
  'clamp-desk-lamp': {
    id: 'clamp-desk-lamp',
    name: 'DIY Clamp Desk Lamp with Diffuser',
    icon: '💡',
    category: 'lighting',
    dimensions: { width: 0.18, depth: 0.18, height: 0.4 },
    watts: 12,
    defaultPriceGHS: 140,
    defaultPriceNGN: 7500,
    color: 0xfffbeb,
    description: 'Flexible gooseneck clamp lamp with parchment diffuser paper for soft, budget-friendly key lighting',
    isMountableOnTable: true,
  },
  'beauty-dish': {
    id: 'beauty-dish',
    name: '55cm Silver Interior Beauty Dish',
    icon: '🍲',
    category: 'lighting',
    dimensions: { width: 0.55, depth: 0.3, height: 1.7 },
    watts: 150,
    defaultPriceGHS: 720,
    defaultPriceNGN: 37000,
    color: 0xd4d0c8,
    description: 'Crisp specular portrait reflector with center deflector disc',
  },
  'barndoor-light': {
    id: 'barndoor-light',
    name: 'Barndoor Studio LED Wash Panel',
    icon: '🚪',
    category: 'lighting',
    dimensions: { width: 0.35, depth: 0.25, height: 1.6 },
    watts: 80,
    defaultPriceGHS: 540,
    defaultPriceNGN: 28000,
    color: 0x22201d,
    description: 'Slim broadcast LED panel with 4 matte metal beam-shaping leaves',
  },
  'beauty-mirror': {
    id: 'beauty-mirror',
    name: 'Hollywood Lighted Vanity Mirror',
    icon: '🪞',
    category: 'lighting',
    dimensions: { width: 0.85, depth: 0.22, height: 0.75 },
    watts: 60,
    defaultPriceGHS: 580,
    defaultPriceNGN: 30000,
    color: 0xffffff,
    description: 'Dimmable glam vanity mirror with perimeter frosted spherical bulbs',
    isMountableOnTable: true,
  },
  'c-stand-flag': {
    id: 'c-stand-flag',
    name: 'Solid Black Cutter Flag (24x36")',
    icon: '🏴',
    category: 'lighting',
    dimensions: { width: 0.75, depth: 0.45, height: 1.9 },
    watts: 0,
    defaultPriceGHS: 240,
    defaultPriceNGN: 12500,
    color: 0x111111,
    description: 'Heavy duvetyne light block flag on 40-inch stainless grip arm',
  },
  'lantern-softbox': {
    id: 'lantern-softbox',
    name: '65cm Omnidirectional Chinese Lantern',
    icon: '🏮',
    category: 'lighting',
    dimensions: { width: 0.65, depth: 0.65, height: 1.9 },
    watts: 200,
    defaultPriceGHS: 420,
    defaultPriceNGN: 22000,
    color: 0xffffff,
    description: '270-degree spherical soft light modifier for natural room ambience',
  },
  'spotlight-mount-gobo': {
    id: 'spotlight-mount-gobo',
    name: 'Optical Spotlight Projector & Gobo Set',
    icon: '🎭',
    category: 'lighting',
    dimensions: { width: 0.35, depth: 0.55, height: 1.8 },
    watts: 300,
    defaultPriceGHS: 1650,
    defaultPriceNGN: 85000,
    color: 0x222222,
    description: 'Precision lens projector with window blind and pattern gobos',
  },
  'rgb-pocket-light': {
    id: 'rgb-pocket-light',
    name: 'Credit-Card Sized RGB Magnetic Video Light',
    icon: '🔦',
    category: 'lighting',
    dimensions: { width: 0.1, depth: 0.03, height: 0.07 },
    watts: 8,
    defaultPriceGHS: 150,
    defaultPriceNGN: 7800,
    color: 0x1a1a1a,
    description: 'OLED screen aluminum pocket light with 360 full hue control',
    isMountableOnTable: true,
  },
  'umbrella-diffuser': {
    id: 'umbrella-diffuser',
    name: '130cm White Translucent Shoot-Through Umbrella',
    icon: '☂️',
    category: 'lighting',
    dimensions: { width: 1.3, depth: 1.3, height: 1.9 },
    watts: 100,
    defaultPriceGHS: 180,
    defaultPriceNGN: 9500,
    color: 0xf0ede6,
    description: 'Broad, wrap-around soft light source for high-key commercial shoots',
  },
  'scrim-jim-frame': {
    id: 'scrim-jim-frame',
    name: '6x6ft Silk Diffusion Scrim Panel Frame',
    icon: '🔲',
    category: 'lighting',
    dimensions: { width: 1.8, depth: 0.6, height: 2.2 },
    watts: 0,
    defaultPriceGHS: 780,
    defaultPriceNGN: 40000,
    color: 0xe8e8e8,
    description: 'Modular aluminum pipe frame with 1-stop silk diffusion fabric',
  },
  'reflector-5in1': {
    id: 'reflector-5in1',
    name: '43-Inch 5-in-1 Collapsible Disc Reflector',
    icon: '🥏',
    category: 'lighting',
    dimensions: { width: 1.1, depth: 0.2, height: 1.6 },
    watts: 0,
    defaultPriceGHS: 120,
    defaultPriceNGN: 6200,
    color: 0xd4af37,
    description: 'Gold, Silver, White, Black and Translucent light modifier panel',
  },
  'optical-snoot': {
    id: 'optical-snoot',
    name: 'Conical Metal Snoot with Honeycomb Grid',
    icon: '🎯',
    category: 'lighting',
    dimensions: { width: 0.15, depth: 0.25, height: 1.5 },
    watts: 60,
    defaultPriceGHS: 190,
    defaultPriceNGN: 9800,
    color: 0x1f1e1d,
    description: 'Narrows beam down to a tight pinpoint circle for hair & rim lighting',
  },
  'rgb-panel-mat': {
    id: 'rgb-panel-mat',
    name: 'Flexible Rollable Waterproof LED Fabric Mat',
    icon: '📜',
    category: 'lighting',
    dimensions: { width: 0.6, depth: 0.45, height: 1.7 },
    watts: 100,
    defaultPriceGHS: 890,
    defaultPriceNGN: 46000,
    color: 0x333333,
    description: 'Ultra-thin pliable LED mat that tapes onto ceilings or car interiors',
  },
  'strobe-flash-monolight': {
    id: 'strobe-flash-monolight',
    name: '600Ws High-Speed Sync Studio Strobe Flash',
    icon: '⚡',
    category: 'lighting',
    dimensions: { width: 0.35, depth: 0.25, height: 1.75 },
    watts: 40,
    defaultPriceGHS: 1350,
    defaultPriceNGN: 70000,
    color: 0x222222,
    description: '1/8000s freeze-motion photography flash with 30W LED modeling lamp',
  },
  'sandbag-counterweight': {
    id: 'sandbag-counterweight',
    name: 'Dual-Wing 10kg Cordura C-Stand Sandbag',
    icon: '👝',
    category: 'lighting',
    dimensions: { width: 0.3, depth: 0.3, height: 0.12 },
    watts: 0,
    defaultPriceGHS: 45,
    defaultPriceNGN: 2300,
    color: 0x1e1d1b,
    description: 'Heavy saddlebag weight to secure boom arms and tall lighting stands',
  },
  'strip-softbox': {
    id: 'strip-softbox',
    name: '30x120cm Vertical Strip Softbox with Grid',
    icon: '📏',
    category: 'lighting',
    dimensions: { width: 0.3, depth: 1.2, height: 1.9 },
    watts: 150,
    defaultPriceGHS: 490,
    defaultPriceNGN: 25500,
    color: 0x1f1e1d,
    description: 'Long slender softbox ideal for edge rim highlights and glass reflections',
  },
  'c-stand-silver': {
    id: 'c-stand-silver',
    name: '10.8ft Chrome Master C-Stand with Grip Arm',
    icon: '🥢',
    category: 'lighting',
    dimensions: { width: 0.45, depth: 0.45, height: 2.2 },
    watts: 0,
    defaultPriceGHS: 380,
    defaultPriceNGN: 19500,
    color: 0x777777,
    description: 'Standard heavy-duty steel turtle base cinema grip stand',
  },
  'gel-color-pack': {
    id: 'gel-color-pack',
    name: 'Color Temperature & Theatrical Gel Filter Set',
    icon: '📑',
    category: 'lighting',
    dimensions: { width: 0.3, depth: 0.3, height: 0.02 },
    watts: 0,
    defaultPriceGHS: 65,
    defaultPriceNGN: 3400,
    color: 0x3388ff,
    description: 'CTO, CTB, Plus Green and 20 vibrant creative effect gel sheets',
    isMountableOnTable: true,
  },
  'dimmer-dmx-console': {
    id: 'dimmer-dmx-console',
    name: '24-Channel Wireless DMX512 Lighting Console',
    icon: '🎛️',
    category: 'lighting',
    dimensions: { width: 0.45, depth: 0.22, height: 0.1 },
    watts: 15,
    defaultPriceGHS: 720,
    defaultPriceNGN: 37000,
    color: 0x22201d,
    description: 'Hardware fader board for programming studio scene cues and color shifts',
    isMountableOnTable: true,
  },
  'floor-uplight-par': {
    id: 'floor-uplight-par',
    name: 'Battery-Powered Wireless RGBWA+UV Uplight Can',
    icon: '🏮',
    category: 'lighting',
    dimensions: { width: 0.2, depth: 0.2, height: 0.22 },
    watts: 45,
    defaultPriceGHS: 310,
    defaultPriceNGN: 16000,
    color: 0x111111,
    description: 'Compact floor uplighter to wash textured walls and columns with color',
  },
  'laser-effect-projector': {
    id: 'laser-effect-projector',
    name: 'RGB Graphic Animation Stage Laser System',
    icon: '💡',
    category: 'lighting',
    dimensions: { width: 0.28, depth: 0.22, height: 0.18 },
    watts: 50,
    defaultPriceGHS: 1450,
    defaultPriceNGN: 75000,
    color: 0x00ffcc,
    description: 'High-speed galvanometer laser projector for beam tunnels and shapes',
  },

  // ------------------------------------------------------------
  // 3. AUDIO & MICROPHONES & SOUND TREATMENT (40 items)
  // ------------------------------------------------------------
  'microphone': {
    id: 'microphone',
    name: 'Condenser Studio Microphone on Boom',
    icon: '🎙️',
    category: 'audio',
    dimensions: { width: 0.3, depth: 0.3, height: 1.4 },
    watts: 0,
    defaultPriceGHS: 480,
    defaultPriceNGN: 25000,
    color: 0x2a2826,
    description: 'Large-diaphragm studio condenser with scissor boom arm and pop filter',
  },
  'lavalier': {
    id: 'lavalier',
    name: 'Dual Wireless Lavalier Clip-on Mic System',
    icon: '📿',
    category: 'audio',
    dimensions: { width: 0.1, depth: 0.05, height: 0.05 },
    watts: 0,
    defaultPriceGHS: 350,
    defaultPriceNGN: 18000,
    color: 0x1f1e1d,
    description: '2.4GHz dual-channel wireless transmitter and receiver with lapel clip',
  },
  'budget-wireless-lav': {
    id: 'budget-wireless-lav',
    name: 'Plug & Play Smartphone Wireless Lapel Mic',
    icon: '🎙️',
    category: 'audio',
    dimensions: { width: 0.08, depth: 0.04, height: 0.04 },
    watts: 2,
    defaultPriceGHS: 240,
    defaultPriceNGN: 12500,
    color: 0x0f172a,
    description: 'Tiny clip-on wireless microphone with direct Lightning / USB-C phone receiver',
    isMountableOnTable: true,
  },
  'audio-recorder': {
    id: 'audio-recorder',
    name: 'Multi-Track 32-Bit Float Audio Field Recorder',
    icon: '📻',
    category: 'audio',
    dimensions: { width: 0.15, depth: 0.1, height: 0.05 },
    watts: 5,
    defaultPriceGHS: 580,
    defaultPriceNGN: 30000,
    color: 0x3a3836,
    description: 'Dual XLR input field recorder with floating-point preamp',
    isMountableOnTable: true,
  },
  'studio-monitor': {
    id: 'studio-monitor',
    name: '5-Inch Active Studio Reference Monitor',
    icon: '🔊',
    category: 'audio',
    dimensions: { width: 0.2, depth: 0.22, height: 0.3 },
    watts: 50,
    defaultPriceGHS: 620,
    defaultPriceNGN: 32000,
    color: 0x1f1e1d,
    description: 'Nearfield bi-amplified studio monitor speaker with Kevlar cone',
    isMountableOnTable: true,
  },
  'podcast-mic': {
    id: 'podcast-mic',
    name: 'Dynamic Broadcast Microphone (SM7B Style)',
    icon: '🎙️',
    category: 'audio',
    dimensions: { width: 0.15, depth: 0.12, height: 0.35 },
    watts: 0,
    defaultPriceGHS: 780,
    defaultPriceNGN: 40000,
    color: 0x22201e,
    description: 'Smooth flat frequency response dynamic mic for voiceovers and radio',
    isMountableOnTable: true,
  },
  'acoustic-panel': {
    id: 'acoustic-panel',
    name: 'High-Density Beveled Acoustic Foam Panel (1x0.5m)',
    icon: '🧱',
    category: 'audio',
    dimensions: { width: 1.0, depth: 0.08, height: 0.5 },
    watts: 0,
    defaultPriceGHS: 95,
    defaultPriceNGN: 4900,
    color: 0x2a2826,
    description: 'NRC 0.90 acoustic treatment panel for absorbing flutter echo',
  },
  'binaural-mic': {
    id: 'binaural-mic',
    name: '3DIO Binaural Silicone Ear Microphone',
    icon: '👂',
    category: 'audio',
    dimensions: { width: 0.28, depth: 0.16, height: 0.22 },
    watts: 0,
    defaultPriceGHS: 980,
    defaultPriceNGN: 51000,
    color: 0xdddddd,
    description: 'Dual anatomical silicone ears for true 3D spatial ASMR recording',
    isMountableOnTable: true,
  },
  'vocal-booth-screen': {
    id: 'vocal-booth-screen',
    name: 'Curved Vocal Isolation Reflection Shield',
    icon: '🛡️',
    category: 'audio',
    dimensions: { width: 0.45, depth: 0.35, height: 0.38 },
    watts: 0,
    defaultPriceGHS: 310,
    defaultPriceNGN: 16000,
    color: 0x1f1e1d,
    description: 'Multi-layer acoustic metal baffle to isolate vocals in unconditioned rooms',
  },
  'shotgun-mic': {
    id: 'shotgun-mic',
    name: 'Directional Shotgun Boom Microphone',
    icon: '🎙️',
    category: 'audio',
    dimensions: { width: 0.35, depth: 0.85, height: 2.1 },
    watts: 0,
    defaultPriceGHS: 680,
    defaultPriceNGN: 35000,
    color: 0x222222,
    description: 'Supercardioid interference tube shotgun on carbon boom pole with deadcat',
  },
  'audio-interface-4ch': {
    id: 'audio-interface-4ch',
    name: '4x4 USB-C High-Resolution Audio Interface',
    icon: '🎛️',
    category: 'audio',
    dimensions: { width: 0.24, depth: 0.16, height: 0.06 },
    watts: 10,
    defaultPriceGHS: 420,
    defaultPriceNGN: 21500,
    color: 0xa82222,
    description: '192kHz 24-bit interface with 4 pristine preamps and MIDI I/O',
    isMountableOnTable: true,
  },
  'studio-headphones': {
    id: 'studio-headphones',
    name: 'Closed-Back Over-Ear Reference Monitor Headphones',
    icon: '🎧',
    category: 'audio',
    dimensions: { width: 0.18, depth: 0.12, height: 0.22 },
    watts: 0,
    defaultPriceGHS: 290,
    defaultPriceNGN: 15000,
    color: 0x1a1918,
    description: '45mm neodymium drivers for critical mixing and noise isolation',
    isMountableOnTable: true,
  },
  'bass-trap-corner': {
    id: 'bass-trap-corner',
    name: 'Triangular Corner Bass Trap (1.2m)',
    icon: '📐',
    category: 'audio',
    dimensions: { width: 0.4, depth: 0.4, height: 1.2 },
    watts: 0,
    defaultPriceGHS: 160,
    defaultPriceNGN: 8200,
    color: 0x1f1e1d,
    description: 'Dense fiberglass corner wedge to tighten low-end room response',
  },
  'subwoofer-studio': {
    id: 'subwoofer-studio',
    name: '10-Inch Powered Studio Subwoofer (200W)',
    icon: '🔊',
    category: 'audio',
    dimensions: { width: 0.38, depth: 0.42, height: 0.4 },
    watts: 200,
    defaultPriceGHS: 950,
    defaultPriceNGN: 49000,
    color: 0x181716,
    description: 'Down-firing bass extension down to 24Hz with bypass footswitch',
  },
  'in-ear-monitor-transmitter': {
    id: 'in-ear-monitor-transmitter',
    name: 'Wireless IEM Transmitter & Bodypack Receiver',
    icon: '📡',
    category: 'audio',
    dimensions: { width: 0.22, depth: 0.18, height: 0.05 },
    watts: 8,
    defaultPriceGHS: 540,
    defaultPriceNGN: 28000,
    color: 0x222222,
    description: 'UHF stereo in-ear monitoring system for presenters and musicians',
    isMountableOnTable: true,
  },
  'mic-cloud-activator': {
    id: 'mic-cloud-activator',
    name: 'Inline +25dB Ultra-Clean Dynamic Mic Preamp',
    icon: '🔋',
    category: 'audio',
    dimensions: { width: 0.12, depth: 0.04, height: 0.04 },
    watts: 0,
    defaultPriceGHS: 140,
    defaultPriceNGN: 7200,
    color: 0x1133aa,
    description: 'Phantom-powered inline signal booster for low-output dynamic mics',
    isMountableOnTable: true,
  },
  'talkback-station': {
    id: 'talkback-station',
    name: 'Control Room Talkback Mic & Matrix Switcher',
    icon: '📻',
    category: 'audio',
    dimensions: { width: 0.22, depth: 0.14, height: 0.25 },
    watts: 10,
    defaultPriceGHS: 310,
    defaultPriceNGN: 16000,
    color: 0x2a2826,
    description: 'Gooseneck microphone console with cue destination routing buttons',
    isMountableOnTable: true,
  },

  // ------------------------------------------------------------
  // 4. FURNITURE, DESKS, SEATING & STAGING (35 items)
  // ------------------------------------------------------------
  'tripod': {
    id: 'tripod',
    name: 'Heavy-Duty Aluminum Light Stand',
    icon: '🗼',
    category: 'furniture',
    dimensions: { width: 0.4, depth: 0.4, height: 1.8 },
    watts: 0,
    defaultPriceGHS: 120,
    defaultPriceNGN: 6200,
    color: 0x2a2826,
    description: 'Air-cushioned light stand extending to 2.8 meters',
  },
  'content-table': {
    id: 'content-table',
    name: 'Solid Wood Production Workstation Desk',
    icon: '🪵',
    category: 'furniture',
    dimensions: { width: 1.4, depth: 0.7, height: 0.75 },
    watts: 0,
    defaultPriceGHS: 850,
    defaultPriceNGN: 44000,
    color: 0x8a6a4a,
    description: 'Sturdy studio table with rear cable management tray',
    surfaceHeight: 0.75,
  },
  'chair': {
    id: 'chair',
    name: 'High-Back Ergonomic Creator Mesh Chair',
    icon: '💺',
    category: 'furniture',
    dimensions: { width: 0.6, depth: 0.6, height: 1.1 },
    watts: 0,
    defaultPriceGHS: 650,
    defaultPriceNGN: 33500,
    color: 0x222222,
    description: 'Breathable mesh chair with 3D armrests and lumbar support',
  },
  'sofa': {
    id: 'sofa',
    name: '2-Seater Modern Studio Lounge Sofa',
    icon: '🛋️',
    category: 'furniture',
    dimensions: { width: 1.6, depth: 0.85, height: 0.8 },
    watts: 0,
    defaultPriceGHS: 1800,
    defaultPriceNGN: 93000,
    color: 0x3d3a36,
    description: 'Upholstered high-resilience foam couch for podcast lounges',
  },
  'bed-furniture': {
    id: 'bed-furniture',
    name: 'Double Bed with Headboard (Owned)',
    icon: '🛏️',
    category: 'furniture',
    dimensions: { width: 1.4, depth: 2.0, height: 0.55 },
    watts: 0,
    defaultPriceGHS: 0,
    defaultPriceNGN: 0,
    color: 0x3b4252,
    description: 'Standard double bed with mattress and pillows — naturally absorbs room audio echo',
  },
  'closet-wardrobe': {
    id: 'closet-wardrobe',
    name: 'Bedroom Wardrobe / Closet (Owned)',
    icon: '🚪',
    category: 'furniture',
    dimensions: { width: 1.0, depth: 0.6, height: 1.9 },
    watts: 0,
    defaultPriceGHS: 0,
    defaultPriceNGN: 0,
    color: 0x4c566a,
    description: 'Tall wardrobe cabinet with clothing — great natural bass trap and background boundary',
  },
  'product-stand': {
    id: 'product-stand',
    name: 'Motorized Rotating 360 Product Turntable',
    icon: '⭕',
    category: 'furniture',
    dimensions: { width: 0.3, depth: 0.3, height: 0.1 },
    watts: 15,
    defaultPriceGHS: 240,
    defaultPriceNGN: 12500,
    color: 0xffffff,
    description: 'Smooth continuous motorized turntable for 360 video spins',
    surfaceHeight: 0.1,
    isMountableOnTable: true,
  },
  'backdrop': {
    id: 'backdrop',
    name: 'Seamless Paper Backdrop Roll on Stand (2.7m)',
    icon: '📜',
    category: 'furniture',
    dimensions: { width: 2.7, depth: 0.5, height: 2.4 },
    watts: 0,
    defaultPriceGHS: 450,
    defaultPriceNGN: 23000,
    color: 0xf0ece1,
    description: 'Heavy duty crossbar stand with seamless neutral grey paper roll',
  },
  'shelf-props': {
    id: 'shelf-props',
    name: 'Modern 4-Tier Background Display Shelf',
    icon: '📚',
    category: 'furniture',
    dimensions: { width: 0.8, depth: 0.35, height: 1.6 },
    watts: 0,
    defaultPriceGHS: 520,
    defaultPriceNGN: 27000,
    color: 0x2d2b28,
    description: 'Industrial matte steel bookcase with wooden display shelves',
  },
  'keyboard-synth': {
    id: 'keyboard-synth',
    name: '61-Key MIDI Synthesizer Keyboard on X-Stand',
    icon: '🎹',
    category: 'furniture',
    dimensions: { width: 0.98, depth: 0.32, height: 0.82 },
    watts: 20,
    defaultPriceGHS: 950,
    defaultPriceNGN: 49000,
    color: 0x1f1e1d,
    description: 'Full-size semi-weighted key synth with pitch bend wheel',
    surfaceHeight: 0.82,
  },
  'dj-deck': {
    id: 'dj-deck',
    name: 'Pioneer 4-Channel DJ Controller Console',
    icon: '🎛️',
    category: 'furniture',
    dimensions: { width: 0.72, depth: 0.38, height: 0.12 },
    watts: 35,
    defaultPriceGHS: 1450,
    defaultPriceNGN: 75000,
    color: 0x181716,
    description: 'Professional DJ controller with dual illuminated jog wheels',
    isMountableOnTable: true,
  },
  'green-screen': {
    id: 'green-screen',
    name: 'Chroma Key Green Screen Backdrop (2x2m)',
    icon: '🟩',
    category: 'furniture',
    dimensions: { width: 2.0, depth: 0.3, height: 2.0 },
    watts: 0,
    defaultPriceGHS: 380,
    defaultPriceNGN: 19500,
    color: 0x00b140,
    description: 'Wrinkle-resistant chromakey green backdrop with tension frame',
  },
  'standing-desk-motorized': {
    id: 'standing-desk-motorized',
    name: 'Dual-Motor Height Adjustable Standing Desk',
    icon: '🖥️',
    category: 'furniture',
    dimensions: { width: 1.6, depth: 0.8, height: 1.15 },
    watts: 40,
    defaultPriceGHS: 1250,
    defaultPriceNGN: 64000,
    color: 0x333333,
    description: 'Memory preset electric sit-stand desk with anti-collision sensor',
    surfaceHeight: 1.15,
  },
  'stool-bar-counter': {
    id: 'stool-bar-counter',
    name: 'Modern Swivel Bar Stool with Footrest',
    icon: '🪑',
    category: 'furniture',
    dimensions: { width: 0.45, depth: 0.45, height: 0.95 },
    watts: 0,
    defaultPriceGHS: 260,
    defaultPriceNGN: 13500,
    color: 0x22201d,
    description: 'Hydraulic lift counter stool for talk show hosts and kitchen sets',
  },
  'mobile-rolling-cart': {
    id: 'mobile-rolling-cart',
    name: '3-Tier Steel Utility Equipment Rolling Cart',
    icon: '🛒',
    category: 'furniture',
    dimensions: { width: 0.75, depth: 0.45, height: 0.9 },
    watts: 0,
    defaultPriceGHS: 340,
    defaultPriceNGN: 17500,
    color: 0x1f1e1d,
    description: 'Heavy duty wheels for staging lens cases, batteries, and snacks',
    surfaceHeight: 0.9,
  },
  'armchair-leather': {
    id: 'armchair-leather',
    name: 'Single Executive Leather Club Armchair',
    icon: '🛋️',
    category: 'furniture',
    dimensions: { width: 0.9, depth: 0.85, height: 0.82 },
    watts: 0,
    defaultPriceGHS: 1100,
    defaultPriceNGN: 57000,
    color: 0x5a3e28,
    description: 'Deep cognac leather armchair for high-end interview sets',
  },
  'coffee-table-round': {
    id: 'coffee-table-round',
    name: 'Mid-Century Round Glass Coffee Table',
    icon: '☕',
    category: 'furniture',
    dimensions: { width: 0.8, depth: 0.8, height: 0.45 },
    watts: 0,
    defaultPriceGHS: 380,
    defaultPriceNGN: 19500,
    color: 0xbb9966,
    description: 'Tempered glass top table for podcast mugs and props',
    surfaceHeight: 0.45,
  },
  'acoustic-partition-screen': {
    id: 'acoustic-partition-screen',
    name: 'Freestanding 3-Panel Acoustic Room Divider',
    icon: '🚪',
    category: 'furniture',
    dimensions: { width: 1.8, depth: 0.15, height: 1.7 },
    watts: 0,
    defaultPriceGHS: 580,
    defaultPriceNGN: 30000,
    color: 0x3d3a36,
    description: 'Movable sound-absorbing folding wall partition on casters',
  },
  'mannequin-torso': {
    id: 'mannequin-torso',
    name: 'Full Body Tailor Form Mannequin on Cast Iron Base',
    icon: '👗',
    category: 'furniture',
    dimensions: { width: 0.45, depth: 0.35, height: 1.75 },
    watts: 0,
    defaultPriceGHS: 320,
    defaultPriceNGN: 16500,
    color: 0xf5f3ee,
    description: 'Adjustable linen draped dressmaker form for fashion lookbooks',
  },

  // ------------------------------------------------------------
  // 5. TECH, COMPUTING, MONITORS & SWITCHERS (30 items)
  // ------------------------------------------------------------
  'stream-deck-xl': {
    id: 'stream-deck-xl',
    name: '32-Key LCD Macro Stream Controller',
    icon: '🎛️',
    category: 'camera',
    dimensions: { width: 0.18, depth: 0.11, height: 0.04 },
    watts: 5,
    defaultPriceGHS: 340,
    defaultPriceNGN: 17500,
    color: 0x1f1e1d,
    description: 'Customizable LCD keys for scene triggers, sound effects, and lights',
    isMountableOnTable: true,
  },
  'curved-ultrawide-monitor': {
    id: 'curved-ultrawide-monitor',
    name: '49-Inch 240Hz Curved UltraWide Gaming Monitor',
    icon: '🖥️',
    category: 'camera',
    dimensions: { width: 1.2, depth: 0.3, height: 0.55 },
    watts: 90,
    defaultPriceGHS: 2400,
    defaultPriceNGN: 124000,
    color: 0x1a1918,
    description: 'Dual-QHD 32:9 super ultrawide display for streaming timeline editing',
    isMountableOnTable: true,
  },
  'dual-monitor-arm': {
    id: 'dual-monitor-arm',
    name: 'Heavy-Duty Gas Spring Dual Monitor Arm',
    icon: '🦾',
    category: 'camera',
    dimensions: { width: 0.8, depth: 0.25, height: 0.45 },
    watts: 0,
    defaultPriceGHS: 190,
    defaultPriceNGN: 9800,
    color: 0x222222,
    description: 'Clamp-on articulating desk mount with integrated cable channels',
    isMountableOnTable: true,
  },
  'rackmount-server-case': {
    id: 'rackmount-server-case',
    name: '12U Studio Equipment Rack Cabinet with Casters',
    icon: '🗄️',
    category: 'furniture',
    dimensions: { width: 0.6, depth: 0.65, height: 0.75 },
    watts: 0,
    defaultPriceGHS: 850,
    defaultPriceNGN: 44000,
    color: 0x111111,
    description: 'Enclosed 19-inch steel audio/video rack with tempered glass door',
  },
  'nas-storage-tower': {
    id: 'nas-storage-tower',
    name: '8-Bay 10GbE High-Speed Video Editing NAS Storage',
    icon: '💾',
    category: 'camera',
    dimensions: { width: 0.28, depth: 0.32, height: 0.24 },
    watts: 85,
    defaultPriceGHS: 2900,
    defaultPriceNGN: 150000,
    color: 0x2a2826,
    description: '100TB RAID array for real-time 8K multi-cam ProRes editing',
    isMountableOnTable: true,
  },

  // ------------------------------------------------------------
  // 6. POWER, BACKUP, CABLES, PROPS & FX (25 items)
  // ------------------------------------------------------------
  'power-station': {
    id: 'power-station',
    name: 'Portable Battery Power Station (1000Wh)',
    icon: '🔋',
    category: 'power',
    dimensions: { width: 0.35, depth: 0.25, height: 0.25 },
    watts: 0,
    defaultPriceGHS: 1800,
    defaultPriceNGN: 93000,
    color: 0x2d2b29,
    description: '1000W pure sine wave inverter battery for location filming',
  },
  'generator': {
    id: 'generator',
    name: 'Silent Inverter Backup Generator (2.5kW)',
    icon: '⚙️',
    category: 'power',
    dimensions: { width: 0.5, depth: 0.3, height: 0.45 },
    watts: 0,
    defaultPriceGHS: 2600,
    defaultPriceNGN: 135000,
    color: 0xb33939,
    description: 'Quiet petrol inverter generator with electric push-button start',
  },
  'power-strip': {
    id: 'power-strip',
    name: 'Surge Protected 8-Outlet Power Strip',
    icon: '🔌',
    category: 'power',
    dimensions: { width: 0.35, depth: 0.08, height: 0.04 },
    watts: 0,
    defaultPriceGHS: 65,
    defaultPriceNGN: 3400,
    color: 0xf0ece1,
    description: 'Heavy duty cord with individual on/off power switches',
    isMountableOnTable: true,
  },
  'fog-machine': {
    id: 'fog-machine',
    name: 'Atmospheric Continuous Stage Haze Machine',
    icon: '💨',
    category: 'props',
    dimensions: { width: 0.42, depth: 0.28, height: 0.26 },
    watts: 700,
    defaultPriceGHS: 490,
    defaultPriceNGN: 25500,
    color: 0x333333,
    description: 'Even oil-free haze generator to make light rays and lasers visible',
  },
  'ups-battery-backup': {
    id: 'ups-battery-backup',
    name: '1500VA Line-Interactive Uninterruptible Power Supply (UPS)',
    icon: '⚡',
    category: 'power',
    dimensions: { width: 0.15, depth: 0.38, height: 0.25 },
    watts: 0,
    defaultPriceGHS: 750,
    defaultPriceNGN: 39000,
    color: 0x1f1e1d,
    description: 'Automatic voltage regulation protecting broadcast PCs and switchers',
  },
  'cable-ramp-protector': {
    id: 'cable-ramp-protector',
    name: 'Heavy-Duty Rubber Floor Cable Protector Ramp (1m)',
    icon: '🚧',
    category: 'power',
    dimensions: { width: 0.25, depth: 1.0, height: 0.05 },
    watts: 0,
    defaultPriceGHS: 85,
    defaultPriceNGN: 4400,
    color: 0xffcc00,
    description: 'High-visibility safety channel preventing tripping over power and SDI cords',
  },
  'extension-cord-reel': {
    id: 'extension-cord-reel',
    name: '25-Meter 16A Heavy Duty Extension Cable Reel',
    icon: '🪢',
    category: 'power',
    dimensions: { width: 0.28, depth: 0.2, height: 0.35 },
    watts: 0,
    defaultPriceGHS: 160,
    defaultPriceNGN: 8200,
    color: 0x2244aa,
    description: 'Industrial thermal-cutout 4-socket power drum',
  },
  'wind-machine-fan': {
    id: 'wind-machine-fan',
    name: 'Variable Speed Studio Wind Blower Fan',
    icon: '🌀',
    category: 'props',
    dimensions: { width: 0.45, depth: 0.3, height: 0.55 },
    watts: 180,
    defaultPriceGHS: 340,
    defaultPriceNGN: 17500,
    color: 0x222222,
    description: 'Silent high-flow fan for flowing hair and dramatic lookbook motion',
  },
  'confetti-cannon': {
    id: 'confetti-cannon',
    name: 'DMX Electric Streamer & Confetti Launcher',
    icon: '🎉',
    category: 'props',
    dimensions: { width: 0.3, depth: 0.3, height: 0.4 },
    watts: 60,
    defaultPriceGHS: 520,
    defaultPriceNGN: 27000,
    color: 0x1a1918,
    description: 'High-pressure celebration burst cannon for stream milestones and podcasts',
  },
  'snow-machine-fx': {
    id: 'snow-machine-fx',
    name: 'High-Volume Silent Stage Foam Snow Machine',
    icon: '❄️',
    category: 'props',
    dimensions: { width: 0.48, depth: 0.28, height: 0.3 },
    watts: 650,
    defaultPriceGHS: 620,
    defaultPriceNGN: 32000,
    color: 0x333333,
    description: 'Throws non-toxic evaporating foam flakes up to 8 meters across the studio',
  },
};
