import type { CreatorTemplate, TemplateItemPlacement as CreatorTemplateItem } from './types';
import { EXTENDED_SCENARIOS } from './scenarios-data';

// ============================================================
// Scenarios Library (100+ Production Scenarios)
// Realistic domain-specific equipment placement for every archetype
// ============================================================

const autoGeneratedScenarios: Record<string, CreatorTemplate> = {};

interface ThemeConfig {
  prefix: string;
  title: string;
  icon: string;
  cat: string;
  baseWidth: number;
  baseDepth: number;
  buildItems: (scale: number, lightType: string, suffix: string) => CreatorTemplateItem[];
}

const THEME_CONFIGS: ThemeConfig[] = [
  // 1. YouTube & Tech Review Studio
  {
    prefix: 'youtube-tech',
    title: 'Tech Review Studio',
    icon: '💻',
    cat: 'Video & Tech',
    baseWidth: 4.4,
    baseDepth: 3.6,
    buildItems: (scale, lightType, suffix) => [
      // 0: Main Workstation Desk
      { equipmentId: 'content-table', x: 0, z: -0.65, rotationY: 0 },
      { equipmentId: 'multi-cam-switcher', x: 0.45, z: -0.6, rotationY: -0.15, parentId: 0 },
      { equipmentId: 'podcast-mic', x: -0.38, z: -0.55, rotationY: 0.2, parentId: 0 },
      { equipmentId: 'studio-monitor', x: -0.55, z: -0.75, rotationY: 0.15, parentId: 0 },
      { equipmentId: 'studio-monitor', x: 0.55, z: -0.75, rotationY: -0.15, parentId: 0 },
      { equipmentId: 'desk-lamp', x: 0.42, z: -0.72, rotationY: 0, parentId: 0, lightSettings: { intensity: 65, colorTempKelvin: 3200, beamAngle: 80 } },
      // Host Chair
      { equipmentId: 'chair', x: 0, z: -0.1, rotationY: 0 },
      // Master Eye-Level Camera
      { equipmentId: 'camera', x: 0, z: 1.15 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '35mm' },
      // Key & Fill Lighting
      { equipmentId: lightType as any, x: -1.4 * scale, z: 0.35, rotationY: Math.PI / 3, lightSettings: { intensity: 85, colorTempKelvin: 5600, beamAngle: 65 } },
      { equipmentId: 'softbox', x: 1.4 * scale, z: 0.35, rotationY: -Math.PI / 3, lightSettings: { intensity: 50, colorTempKelvin: 4500, beamAngle: 75 } },
      // Acoustic wall baffles & shelf
      { equipmentId: 'acoustic-panel', x: -1.2, z: -1.6, rotationY: 0 },
      { equipmentId: 'acoustic-panel', x: 1.2, z: -1.6, rotationY: 0 },
      { equipmentId: 'shelf-props', x: -1.6, z: -1.1, rotationY: Math.PI / 2 },
      { equipmentId: 'power-station', x: 1.6 * scale, z: -1.1, rotationY: 0 },
    ],
  },

  // 2. Broadcast Podcast Room
  {
    prefix: 'podcast-pro',
    title: 'Broadcast Podcast Lounge',
    icon: '🎙️',
    cat: 'Audio & Music',
    baseWidth: 5.2,
    baseDepth: 4.2,
    buildItems: (scale, lightType, suffix) => [
      { equipmentId: 'backdrop', x: 0, z: -1.8, rotationY: 0 },
      // Host and Guest Seating
      { equipmentId: 'sofa', x: 0, z: -0.85, rotationY: 0 },
      // 2: Central Coffee & Gear Table
      { equipmentId: 'content-table', x: 0, z: -0.1, rotationY: 0 },
      { equipmentId: 'podcast-mic', x: -0.4, z: -0.1, rotationY: 0.2, parentId: 2 },
      { equipmentId: 'podcast-mic', x: 0.4, z: -0.1, rotationY: -0.2, parentId: 2 },
      { equipmentId: 'audio-recorder', x: 0, z: -0.1, rotationY: 0, parentId: 2 },
      // Master Camera & B-Cam Angle
      { equipmentId: 'camera', x: 0, z: 1.5 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '35mm' },
      { equipmentId: 'camera', x: -1.4 * scale, z: 1.0, rotationY: Math.PI * 0.75, lensPreset: '85mm' },
      // Lighting
      { equipmentId: lightType as any, x: -1.8 * scale, z: 0.5, rotationY: Math.PI / 3, lightSettings: { intensity: 85, colorTempKelvin: 5600, beamAngle: 60 } },
      { equipmentId: 'softbox', x: 1.8 * scale, z: 0.5, rotationY: -Math.PI / 3, lightSettings: { intensity: 55, colorTempKelvin: 4500, beamAngle: 75 } },
      { equipmentId: 'rgb-tube', x: 1.3, z: -1.5, rotationY: -Math.PI / 2, lightSettings: { intensity: 70, colorHex: '#00D4FF', beamAngle: 120 } },
      // Acoustics
      { equipmentId: 'acoustic-panel', x: -2.3 * scale, z: -0.8, rotationY: Math.PI / 2 },
      { equipmentId: 'acoustic-panel', x: 2.3 * scale, z: -0.8, rotationY: -Math.PI / 2 },
      { equipmentId: 'power-station', x: -2.0, z: -1.5, rotationY: 0 },
    ],
  },

  // 3. Culinary & Cooking Show
  {
    prefix: 'cooking-asmr',
    title: 'Culinary Cooking Set',
    icon: '🍳',
    cat: 'Lifestyle & Crafts',
    baseWidth: 5.4,
    baseDepth: 4.4,
    buildItems: (scale, lightType, suffix) => [
      { equipmentId: 'backdrop', x: 0, z: -1.9, rotationY: 0 },
      // 1: Center Prep Kitchen Island
      { equipmentId: 'content-table', x: 0, z: -0.4, rotationY: 0 },
      { equipmentId: 'product-stand', x: 0, z: -0.4, rotationY: 0, parentId: 1 },
      // Overhead Rig pointing straight down at chopping board
      { equipmentId: 'overhead-rig', x: -0.3, z: -0.4, rotationY: 0 },
      // Master Eye-Level Camera
      { equipmentId: 'camera', x: 0, z: 1.6 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '50mm' },
      // Floor confidence monitor for chef preview
      { equipmentId: 'floor-monitor', x: 0.9, z: 1.1, rotationY: Math.PI * 0.85 },
      // Lighting
      { equipmentId: lightType as any, x: -1.8 * scale, z: 0.4, rotationY: Math.PI / 3, lightSettings: { intensity: 90, colorTempKelvin: 5600, beamAngle: 60 } },
      { equipmentId: 'softbox', x: 1.8 * scale, z: 0.4, rotationY: -Math.PI / 3, lightSettings: { intensity: 60, colorTempKelvin: 5600, beamAngle: 60 } },
      // Wireless audio & pantry shelf
      { equipmentId: 'lavalier', x: 0, z: -0.1, rotationY: 0 },
      { equipmentId: 'shelf-props', x: -2.1 * scale, z: -1.4, rotationY: Math.PI / 2 },
      { equipmentId: 'power-station', x: 2.1 * scale, z: -1.4, rotationY: 0 },
    ],
  },

  // 4. Fashion Runway & Lookbook
  {
    prefix: 'fashion-glam',
    title: 'Fashion Runway Studio',
    icon: '👗',
    cat: 'Commercial & Photo',
    baseWidth: 5.8,
    baseDepth: 5.2,
    buildItems: (scale, lightType, suffix) => [
      { equipmentId: 'backdrop', x: 0, z: -2.2, rotationY: 0 },
      // Full-length master camera on fluid head tripod
      { equipmentId: 'camera', x: 0, z: 2.2 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '85mm' },
      // Overhead beauty dish for cheekbone highlight
      { equipmentId: 'beauty-dish', x: 0, z: -0.4, rotationY: Math.PI, lightSettings: { intensity: 85, colorTempKelvin: 5600, beamAngle: 45 } },
      // Dual high-power softbox washes
      { equipmentId: lightType as any, x: -2.0 * scale, z: 0.6, rotationY: Math.PI / 3 },
      { equipmentId: 'softbox', x: 2.0 * scale, z: 0.6, rotationY: -Math.PI / 3 },
      // Rim accent lights
      { equipmentId: 'led-light', x: -2.4 * scale, z: -1.0, rotationY: Math.PI / 2 },
      { equipmentId: 'led-light', x: 2.4 * scale, z: -1.0, rotationY: -Math.PI / 2 },
      // Wardrobe prep corner
      { equipmentId: 'shelf-props', x: -2.3 * scale, z: -2.1, rotationY: 0 },
      { equipmentId: 'chair', x: 2.1 * scale, z: -1.6, rotationY: -Math.PI / 4 },
      { equipmentId: 'power-station', x: -2.4, z: 1.8, rotationY: 0 },
    ],
  },

  // 5. Fitness & Workout Stage
  {
    prefix: 'fitness-hiit',
    title: 'Fitness Workout Stage',
    icon: '🧘',
    cat: 'Lifestyle & Crafts',
    baseWidth: 6.0,
    baseDepth: 4.8,
    buildItems: (scale, lightType, suffix) => [
      { equipmentId: 'backdrop', x: 0, z: -2.1, rotationY: 0 },
      // Wide open workout space
      { equipmentId: 'floor-monitor', x: 1.0, z: 1.5, rotationY: Math.PI * 0.85 },
      // Master Wide Camera (24mm for full-body jumps)
      { equipmentId: 'camera', x: 0, z: 2.0 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '24mm' },
      // Dual broad wash softboxes
      { equipmentId: lightType as any, x: -2.2 * scale, z: 0.5, rotationY: Math.PI / 3 },
      { equipmentId: 'softbox', x: 2.2 * scale, z: 0.5, rotationY: -Math.PI / 3 },
      { equipmentId: 'beauty-dish', x: 0, z: -0.6, rotationY: Math.PI },
      // Side props table for water/weights
      { equipmentId: 'content-table', x: 2.3 * scale, z: -1.5, rotationY: -Math.PI / 6 },
      { equipmentId: 'lavalier', x: 0, z: 0, rotationY: 0 },
      { equipmentId: 'power-station', x: -2.4 * scale, z: 1.7, rotationY: 0 },
    ],
  },

  // 6. ASMR & Spatial Audio
  {
    prefix: 'asmr-whisper',
    title: 'Spatial ASMR Chamber',
    icon: '🎧',
    cat: 'Audio & Music',
    baseWidth: 4.0,
    baseDepth: 3.4,
    buildItems: (scale, lightType, suffix) => [
      // 0: Center ASMR Desk
      { equipmentId: 'content-table', x: 0, z: -0.45, rotationY: 0 },
      { equipmentId: 'binaural-mic', x: 0, z: -0.42, rotationY: 0, parentId: 0 },
      { equipmentId: 'desk-lamp', x: -0.42, z: -0.5, rotationY: 0, parentId: 0, lightSettings: { intensity: 60, colorTempKelvin: 2800, beamAngle: 80 } },
      { equipmentId: 'desk-lamp', x: 0.42, z: -0.5, rotationY: 0, parentId: 0, lightSettings: { intensity: 60, colorTempKelvin: 2800, beamAngle: 80 } },
      // Host Stool
      { equipmentId: 'chair', x: 0, z: 0.1, rotationY: 0 },
      // Macro Front Camera
      { equipmentId: 'camera', x: 0, z: 0.95 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '50mm' },
      // Dual Subtle Ambient Glow Tubes behind host
      { equipmentId: lightType === 'rgb-tube' ? 'rgb-tube' : 'rgb-tube', x: -1.3 * scale, z: -1.1, rotationY: Math.PI / 4, lightSettings: { intensity: 60, colorHex: '#FF7700', beamAngle: 120 } },
      { equipmentId: 'rgb-tube', x: 1.3 * scale, z: -1.1, rotationY: -Math.PI / 4, lightSettings: { intensity: 60, colorHex: '#00D4FF', beamAngle: 120 } },
      // Heavy Wall Acoustic Treatment
      { equipmentId: 'acoustic-panel', x: -0.8, z: -1.5, rotationY: 0 },
      { equipmentId: 'acoustic-panel', x: 0.8, z: -1.5, rotationY: 0 },
      { equipmentId: 'acoustic-panel', x: -1.8 * scale, z: 0, rotationY: Math.PI / 2 },
      { equipmentId: 'acoustic-panel', x: 1.8 * scale, z: 0, rotationY: -Math.PI / 2 },
      { equipmentId: 'power-station', x: -1.4, z: 0.8, rotationY: 0 },
    ],
  },

  // 7. Electronic Synth & Music Studio
  {
    prefix: 'music-synth',
    title: 'Electronic Synth Lab',
    icon: '🎹',
    cat: 'Audio & Music',
    baseWidth: 5.0,
    baseDepth: 4.2,
    buildItems: (scale, lightType, suffix) => [
      // 0: Producer Workstation Desk
      { equipmentId: 'content-table', x: 0, z: -0.9, rotationY: 0 },
      { equipmentId: 'studio-monitor', x: -0.55, z: -0.92, rotationY: 0.15, parentId: 0 },
      { equipmentId: 'studio-monitor', x: 0.55, z: -0.92, rotationY: -0.15, parentId: 0 },
      { equipmentId: 'audio-recorder', x: 0, z: -0.85, rotationY: 0, parentId: 0 },
      { equipmentId: 'desk-lamp', x: 0.4, z: -0.9, rotationY: 0, parentId: 0 },
      // Producer Chair
      { equipmentId: 'chair', x: 0, z: -0.3, rotationY: 0 },
      // 61-Key Synth Keyboard on Stand
      { equipmentId: 'keyboard-synth', x: 1.5 * scale, z: -0.6, rotationY: -Math.PI / 2 },
      // Vocal Reflection Shield in Recording Corner
      { equipmentId: 'vocal-booth-screen', x: -1.5 * scale, z: 0.4, rotationY: Math.PI * 0.75 },
      // Master Camera
      { equipmentId: 'camera', x: 0, z: 1.3 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '35mm' },
      // Neon & Lighting
      { equipmentId: lightType as any, x: -1.7 * scale, z: 0.6, rotationY: Math.PI / 3 },
      { equipmentId: 'rgb-tube', x: -1.6, z: -1.5, rotationY: Math.PI / 4, lightSettings: { intensity: 75, colorHex: '#9D00FF', beamAngle: 120 } },
      { equipmentId: 'rgb-tube', x: 1.6, z: -1.5, rotationY: -Math.PI / 4, lightSettings: { intensity: 75, colorHex: '#00E5FF', beamAngle: 120 } },
      // Acoustic wall tiles
      { equipmentId: 'acoustic-panel', x: -1.2, z: -1.9, rotationY: 0 },
      { equipmentId: 'acoustic-panel', x: 1.2, z: -1.9, rotationY: 0 },
      { equipmentId: 'power-station', x: 1.8 * scale, z: 1.3, rotationY: 0 },
    ],
  },

  // 8. Commercial Product Bay
  {
    prefix: 'photo-hero',
    title: 'Product Commercial Bay',
    icon: '📸',
    cat: 'Commercial & Photo',
    baseWidth: 4.6,
    baseDepth: 3.8,
    buildItems: (scale, lightType, suffix) => [
      { equipmentId: 'backdrop', x: 0, z: -1.4, rotationY: 0 },
      // Motorized turntable product stand
      { equipmentId: 'product-stand', x: 0, z: -0.4, rotationY: 0 },
      // High-precision macro camera on slider
      { equipmentId: 'camera-slider', x: 0, z: 0.95 * scale, rotationY: 0 },
      { equipmentId: 'camera', x: 0, z: 0.95 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '50mm' },
      // Reflection control C-Stand Flags
      { equipmentId: 'c-stand-flag', x: -0.85, z: -0.4, rotationY: Math.PI / 6 },
      { equipmentId: 'c-stand-flag', x: 0.85, z: -0.4, rotationY: -Math.PI / 6 },
      // Overhead Beauty Dish
      { equipmentId: 'beauty-dish', x: 0, z: -0.4, rotationY: Math.PI, lightSettings: { intensity: 85, colorTempKelvin: 5600, beamAngle: 45 } },
      // Dual high-CRI softboxes
      { equipmentId: lightType as any, x: -1.5 * scale, z: 0.15, rotationY: Math.PI / 3, lightSettings: { intensity: 90, colorTempKelvin: 5600, beamAngle: 60 } },
      { equipmentId: 'softbox', x: 1.5 * scale, z: 0.15, rotationY: -Math.PI / 3, lightSettings: { intensity: 60, colorTempKelvin: 5600, beamAngle: 60 } },
      { equipmentId: 'shelf-props', x: -1.7 * scale, z: -1.2, rotationY: Math.PI / 2 },
      { equipmentId: 'power-station', x: 1.6 * scale, z: -1.2, rotationY: 0 },
    ],
  },

  // 9. Executive Webinar Suite
  {
    prefix: 'webinar-exec',
    title: 'Executive Webinar Suite',
    icon: '🏛️',
    cat: 'Commercial & Photo',
    baseWidth: 5.2,
    baseDepth: 4.2,
    buildItems: (scale, lightType, suffix) => [
      // 0: Executive Desk
      { equipmentId: 'content-table', x: 0, z: -0.75, rotationY: 0 },
      { equipmentId: 'podcast-mic', x: -0.4, z: -0.7, rotationY: 0.2, parentId: 0 },
      { equipmentId: 'desk-lamp', x: 0.45, z: -0.75, rotationY: 0, parentId: 0 },
      // Leather Executive Chair
      { equipmentId: 'chair', x: 0, z: -0.15, rotationY: 0 },
      // Beam-Splitter Teleprompter + Camera Rig
      { equipmentId: 'teleprompter', x: 0, z: 1.35 * scale, rotationY: Math.PI },
      { equipmentId: 'camera', x: 0, z: 1.35 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '50mm' },
      // Floor confidence slide monitor
      { equipmentId: 'floor-monitor', x: 0.85, z: 0.7, rotationY: Math.PI * 0.75 },
      // Dual Barndoor Spotlights
      { equipmentId: lightType as any, x: -1.7 * scale, z: 0.45, rotationY: Math.PI / 3 },
      { equipmentId: 'barndoor-light', x: 1.7 * scale, z: 0.45, rotationY: -Math.PI / 3 },
      // Bookcase props and acoustic wall panel
      { equipmentId: 'shelf-props', x: -1.9 * scale, z: -1.4, rotationY: Math.PI / 2 },
      { equipmentId: 'acoustic-panel', x: 0.7, z: -1.9, rotationY: 0 },
      { equipmentId: 'power-station', x: 1.8 * scale, z: -1.4, rotationY: 0 },
    ],
  },

  // 10. Compact Dorm & Bedroom Creator Nook
  {
    prefix: 'dorm-nook',
    title: 'Compact Creator Nook',
    icon: '🛏️',
    cat: 'Bedroom & Small',
    baseWidth: 3.4,
    baseDepth: 2.8,
    buildItems: (scale, lightType, suffix) => [
      // Bed for space reality and room echo absorption
      { equipmentId: 'bed-furniture', x: -0.95, z: -0.4, rotationY: 0 },
      // 1: Small Compact Work Desk
      { equipmentId: 'content-table', x: 0.35, z: 0.15, rotationY: 0 },
      { equipmentId: 'webcam', x: 0.35, z: 0.15, rotationY: Math.PI, parentId: 1, lensPreset: '24mm' },
      { equipmentId: 'desk-lamp', x: 0.7, z: 0.15, rotationY: 0, parentId: 1 },
      { equipmentId: 'podcast-mic', x: 0.05, z: 0.2, rotationY: 0, parentId: 1 },
      // Desk Chair
      { equipmentId: 'chair', x: 0.35, z: -0.55, rotationY: 0 },
      // Front Camera / Smartphone Mount
      { equipmentId: 'camera', x: 0.35, z: 1.0 * scale, rotationY: Math.PI, isMainCamera: true, lensPreset: '24mm' },
      // Key Lighting
      { equipmentId: lightType as any, x: 0.95 * scale, z: 0.6, rotationY: -Math.PI / 4 },
      // Acoustic wall foam
      { equipmentId: 'acoustic-panel', x: 0.35, z: -1.25, rotationY: 0 },
      { equipmentId: 'power-strip', x: 0.9, z: -0.6, rotationY: 0 },
    ],
  },
];

const VARIATIONS = [
  { sub: 'v1-minimal', suffix: 'Minimalist Starter', scale: 1.0, light: 'ring-light' },
  { sub: 'v2-rgb', suffix: 'RGB Cyberpunk Neon', scale: 1.08, light: 'rgb-tube' },
  { sub: 'v3-multicam', suffix: '3-Camera Pro Live', scale: 1.18, light: 'softbox' },
  { sub: 'v4-broadcast', suffix: 'High-End Broadcast Spec', scale: 1.25, light: 'fresnel' },
  { sub: 'v5-mobile', suffix: 'Fast Battery Powered', scale: 1.0, light: 'barndoor-light' },
  { sub: 'v6-isolation', suffix: 'Acoustic Dampened Max', scale: 1.12, light: 'softbox' },
  { sub: 'v7-highkey', suffix: 'High-Key Commercial White', scale: 1.2, light: 'beauty-dish' },
  { sub: 'v8-cinematic', suffix: 'Cinematic Mood & Haze', scale: 1.25, light: 'fresnel' },
];

// Generate distinct, high-fidelity combinations
for (const theme of THEME_CONFIGS) {
  for (const v of VARIATIONS) {
    const id = `${theme.prefix}-${v.sub}`;
    const roomW = +(theme.baseWidth * v.scale).toFixed(1);
    const roomD = +(theme.baseDepth * v.scale).toFixed(1);
    
    autoGeneratedScenarios[id] = {
      id: id as any,
      name: `${theme.title} (${v.suffix})`,
      icon: theme.icon,
      category: theme.cat,
      description: `Tailored ${theme.title.toLowerCase()} configured for ${v.suffix.toLowerCase()} with optimized acoustic, camera, and lighting placement.`,
      defaultRoom: { width: roomW, depth: roomD },
      items: theme.buildItems(v.scale, v.light, v.suffix),
    };
  }
}

// Master combined scenario catalog (100+ scenarios)
export const ALL_STUDIO_SCENARIOS: Record<string, CreatorTemplate> = {
  ...EXTENDED_SCENARIOS,
  ...autoGeneratedScenarios,
};

export const ALL_SCENARIO_IDS: string[] = Object.keys(ALL_STUDIO_SCENARIOS);

