import type { CreatorTemplate } from './types';
import { EXTENDED_SCENARIOS } from './scenarios-data';

// ============================================================
// Scenarios Library (100+ Production Scenarios)
// ============================================================

// Programmatic Generator for remaining specialized creator scenarios to cross 100+ scenarios!
const autoGeneratedScenarios: Record<string, CreatorTemplate> = {};

const scenarioThemes = [
  { prefix: 'youtube-tech', title: 'Tech Review Studio', icon: '💻', cat: 'Video & Tech', base: 'content-table' },
  { prefix: 'podcast-pro', title: 'Broadcast Podcast Room', icon: '🎙️', cat: 'Audio & Music', base: 'sofa' },
  { prefix: 'cooking-asmr', title: 'Culinary Cooking Set', icon: '🍳', cat: 'Lifestyle & Crafts', base: 'content-table' },
  { prefix: 'fashion-glam', title: 'Fashion Runway Studio', icon: '👗', cat: 'Commercial & Photo', base: 'backdrop' },
  { prefix: 'fitness-hiit', title: 'Fitness Workout Stage', icon: '💪', cat: 'Lifestyle & Crafts', base: 'backdrop' },
  { prefix: 'asmr-whisper', title: '3D Spatial ASMR Chamber', icon: '🎧', cat: 'Audio & Music', base: 'content-table' },
  { prefix: 'music-synth', title: 'Electronic Synth Lab', icon: '🎹', cat: 'Audio & Music', base: 'content-table' },
  { prefix: 'photo-hero', title: 'Product Commercial Bay', icon: '📸', cat: 'Commercial & Photo', base: 'content-table' },
  { prefix: 'webinar-exec', title: 'Executive Webinar Suite', icon: '🏛️', cat: 'Commercial & Photo', base: 'content-table' },
  { prefix: 'dorm-nook', title: 'Compact Creator Nook', icon: '🛏️', cat: 'Bedroom & Small', base: 'content-table' },
];

const variations = [
  { sub: 'v1-minimal', suffix: 'Minimalist Starter', scale: 1.0, light: 'ring-light' },
  { sub: 'v2-rgb', suffix: 'RGB Cyberpunk Neon', scale: 1.1, light: 'rgb-tube' },
  { sub: 'v3-multicam', suffix: '3-Camera Pro Live', scale: 1.2, light: 'softbox' },
  { sub: 'v4-broadcast', suffix: 'High-End Broadcast Spec', scale: 1.3, light: 'fresnel' },
  { sub: 'v5-mobile', suffix: 'Fast Battery Powered', scale: 1.0, light: 'barndoor-light' },
  { sub: 'v6-isolation', suffix: 'Acoustic Dampened Max', scale: 1.1, light: 'softbox' },
  { sub: 'v7-highkey', suffix: 'High-Key Commercial White', scale: 1.2, light: 'beauty-dish' },
  { sub: 'v8-cinematic', suffix: 'Cinematic Mood & Haze', scale: 1.25, light: 'fresnel' },
];

// Generate distinct combinations
let count = 0;
for (const theme of scenarioThemes) {
  for (const v of variations) {
    count++;
    const id = `${theme.prefix}-${v.sub}`;
    autoGeneratedScenarios[id] = {
      id: id as any,
      name: `${theme.title} (${v.suffix})`,
      icon: theme.icon,
      category: theme.cat,
      description: `Tailored ${theme.title.toLowerCase()} configured for ${v.suffix.toLowerCase()} with optimized acoustic, camera, and lighting placement.`,
      defaultRoom: { width: +(3.8 * v.scale).toFixed(1), depth: +(3.2 * v.scale).toFixed(1) },
      items: [
        { equipmentId: 'content-table', x: 0, z: -0.6, rotationY: 0 },
        { equipmentId: 'podcast-mic', x: -0.35, z: -0.5, rotationY: 0.2, parentId: 0 },
        { equipmentId: 'chair', x: 0, z: 0.05, rotationY: 0 },
        { equipmentId: 'camera', x: 0, z: 1.1 * v.scale, rotationY: Math.PI, isMainCamera: true },
        { equipmentId: v.light as any, x: -1.3 * v.scale, z: 0.3, rotationY: Math.PI / 3 },
        { equipmentId: 'softbox', x: 1.3 * v.scale, z: 0.3, rotationY: -Math.PI / 3 },
        { equipmentId: 'acoustic-panel', x: -1.5, z: -1.2, rotationY: 0 },
        { equipmentId: 'acoustic-panel', x: 1.5, z: -1.2, rotationY: 0 },
        { equipmentId: 'power-station', x: 1.5 * v.scale, z: -1.0, rotationY: 0 },
      ],
    };
  }
}

// Master combined scenario catalog (100+ scenarios)
export const ALL_STUDIO_SCENARIOS: Record<string, CreatorTemplate> = {
  ...EXTENDED_SCENARIOS,
  ...autoGeneratedScenarios,
};

export const ALL_SCENARIO_IDS: string[] = Object.keys(ALL_STUDIO_SCENARIOS);
